name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            cpu: amd64
          - os: linux
            cpu: i386
          - os: linux-gcc-14
            cpu: amd64
          - os: macos
            cpu: amd64
          - os: macos-14
            cpu: arm64
          - os: windows
            cpu: amd64
        nim:
          - ref: version-1-6
            memory_management: refc
          - ref: version-2-0
            memory_management: refc
        include:
          - platform:
              os: linux
            builder: ubuntu-22.04
            shell: bash
          - platform:
              os: linux-gcc-14
            builder: ubuntu-24.04
            shell: bash
          - platform:
              os: macos
            builder: macos-13
            shell: bash
          - platform:
              os: macos-14
            builder: macos-14
            shell: bash
          - platform:
              os: windows
            builder: windows-2022
            shell: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: '${{ matrix.platform.os }}-${{ matrix.platform.cpu }} (Nim ${{ matrix.nim.ref }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Nim
        uses: "./.github/actions/install_nim"
        with:
          os: ${{ matrix.platform.os }}
          cpu: ${{ matrix.platform.cpu }}
          shell: ${{ matrix.shell }}
          nim_ref: ${{ matrix.nim.ref }}

      # Restore p2pd from cache
      - name: Restore p2pd from cache
        id: p2pd-cache
        uses: actions/cache@v3
        with:
          path: .ci-bin
          key: p2pd-${{ matrix.platform.os }}-${{ matrix.platform.cpu }}-v0.9.1-2  # Increment version to invalidate old cache

      # For macOS arm64, always build from source, it's more reliable
      - name: Setup Go for macOS arm64
        if: matrix.platform.os == 'macos-14' && matrix.platform.cpu == 'arm64'
        uses: actions/setup-go@v5
        with:
          go-version: '~1.16.0'

      - name: Build p2pd from source for macOS arm64
        if: matrix.platform.os == 'macos-14' && matrix.platform.cpu == 'arm64'
        run: |
          mkdir -p .ci-bin
          # Remove any placeholder script from previous runs
          rm -f .ci-bin/p2pd
          
          # Build from source
          echo "Building p2pd from source for macOS arm64..."
          V=1 bash scripts/build_p2pd.sh p2pdCache 124530a3
          
          # Debug to see where the binary ended up
          echo "Checking for built binaries:"
          find . -name "p2pd*" -type f
          
          # Ensure binary was built and is in .ci-bin
          if [ -f p2pd ]; then
            echo "Moving p2pd to .ci-bin directory"
            mv p2pd .ci-bin/p2pd
            chmod +x .ci-bin/p2pd
          else
            echo "ERROR: p2pd binary not found after build!"
            exit 1
          fi
          
          # Add to PATH and verify it works
          export PATH="${{ github.workspace }}/.ci-bin:$PATH"
          echo "Verifying p2pd is working:"
          .ci-bin/p2pd --version || echo "Warning: p2pd version check failed"
          
          echo "${{ github.workspace }}/.ci-bin" >> $GITHUB_PATH

      # For all other platforms, use pre-built binaries
      - name: Install p2pd binary for non-macOS-arm64 platforms
        if: (!(matrix.platform.os == 'macos-14' && matrix.platform.cpu == 'arm64')) && steps.p2pd-cache.outputs.cache-hit != 'true'
        uses: "./.github/actions/install_p2pd"
        with:
          os: ${{ matrix.platform.os }}
          cpu: ${{ matrix.platform.cpu }}

      # Verify p2pd installation for all platforms
      - name: Verify p2pd installation
        run: |
          echo "Verifying p2pd installation in .ci-bin:"
          mkdir -p .ci-bin
          ls -la .ci-bin/
          
          # Make sure binary is executable
          if [[ "${{ matrix.platform.os }}" != windows* ]]; then
            chmod +x .ci-bin/p2pd || true
          fi
          
          # Add to PATH
          echo "${{ github.workspace }}/.ci-bin" >> $GITHUB_PATH
          export PATH="${{ github.workspace }}/.ci-bin:$PATH"
          
          # Test and validate the binary
          echo "Testing p2pd from PATH:"
          which p2pd || which p2pd.exe || echo "p2pd not found in PATH!"
          
          if [[ "${{ matrix.platform.os }}" == windows* ]]; then
            .ci-bin/p2pd.exe --version || echo "Warning: p2pd version check failed!"
          else
            .ci-bin/p2pd --version || echo "Warning: p2pd version check failed!"
          fi
          
          # Debug: display PATH
          echo "PATH environment variable:"
          echo $PATH

      # Rest of the CI steps
      - name: Restore deps from cache
        id: deps-cache
        uses: actions/cache@v3
        with:
          path: nimbledeps
          key: nimbledeps-${{ matrix.nim.ref }}-${{ matrix.builder }}-${{ matrix.platform.cpu }}-${{ hashFiles('.pinned') }}

      - name: Setup python
        run: |
          mkdir -p .venv
          python -m venv .venv

      - name: Install deps
        if: ${{ steps.deps-cache.outputs.cache-hit != 'true' }}
        run: |
          source .venv/bin/activate
          nimble install_pinned

      - name: Use gcc 14
        if: ${{ matrix.platform.os == 'linux-gcc-14' }}
        run: |
          # Add GCC-14 to alternatives
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14
          # Set GCC-14 as the default
          sudo update-alternatives --set gcc /usr/bin/gcc-14

      - name: Run tests
        run: |
          source .venv/bin/activate
          nim --version
          nimble --version
          gcc --version
          
          # Debug: Verify p2pd is still in PATH before running tests
          which p2pd || which p2pd.exe || echo "Warning: p2pd not found in PATH before tests!"
          
          if [[ "${{ matrix.platform.os }}" == windows* ]]; then
            p2pd.exe --version || echo "Warning: p2pd version check failed before tests!"
          else
            p2pd --version || echo "Warning: p2pd version check failed before tests!"
          fi
          
          NIMFLAGS="${NIMFLAGS} --mm:${{ matrix.nim.memory_management }}"
          nimble test
